### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jeffreyjseamanppu**
Adding images to support a visual view of logging into the jumpbox environment to support the secured jail account.

### CODE REVIEW

**Comment by jeffreyjseamanppu** [comment]
Creating a visual to support Dr. Voortmans documentation for the jumpbox.

**Comment by markvoortmanppu** [comment]
Does it make sense to link these images in `jump-box.md`?

**Comment by jeffreyjseamanppu** [comment]
It doesn't matter to me, I was just trying to be consistent on where images were stored. Wasn't sure how you were doing it. No preference.

**Comment by markvoortmanppu** [comment]
The location of the images makes perfect sense, I was just wondering if we should update the contents of `jump-box.md` so that students see the images when looking at that page (i.e., https://appliedcomputerscience.org/jump-box).
Right now the only way to access the images would be with the direct URL.

**Comment by jeffreyjseamanppu** [comment]
That works.

**Review by markvoortmanppu — APPROVED** [review]
Merging this but still need to update `jump-box.md` to link to the images.

**Pull request merged**
